# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  self:
    path: mbus-app

  # List of git repositories which make up the application
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.6.0
      import: true

    - name: mbus
      url: https://github.com/kartben/zephyr-mbus-module
      revision: main
      submodules: true
      path: modules/lib/mbus
